### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#1]
## Value proposition

**As a** user
**I need** have an issue overview
**to be able to** have the latest react issues on github

## Description
<img width="700" src="https://user-images.githubusercontent.com/93412094/156600313-79fbd158-c622-4c65-8bab-acf6e28c0025.svg" alt="Dashboard"/>

## Acceptance Criteria

- [x] Fetch with a loading and an error state
- [x] List of issues appears after a successful fetch

## Tasks

- [x] Global styles
- [x] services/Fetch
- [x] pages/Dashboard
    - [x] Storybook
    - [x] Add loading state
    - [x] Add error state
    - [x] Tests
    - [x] Styling
- [x] components/IssueList
    - [x] Storybook
    - [x] Tests
    - [x] Styling
- [x] Add to app
- [x] check on mobile device
- [x] check accessibility
