### ISSUE TITLE
Remove issues

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#10]
## Value proposition

**As a** user
**I need** to remove issues
**to be able to** clean up the storage

## Description
<img width="400" src="https://user-images.githubusercontent.com/93412094/159340054-226c313c-d4b7-475a-a317-79a9e9a1792e.svg" alt="Detail page with a remove button" />

## Acceptance Criteria

- [x] A popup to confirm the deletion will appear
- [x] After confirming, the issue will be removed

## Tasks

- [x] update components/Detail
- [x] Update test
- [x] Update README.md
- [x] Add to app
