### ISSUE TITLE
Edit issues

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#11]
## Value proposition

**As a** user
**I need** to edit issues
**to be able to** update them

## Description
<img width="400" src="https://user-images.githubusercontent.com/93412094/157831777-aabd499b-5265-4e63-a0b3-07ca415b94c0.svg" alt="Selection" />

## Acceptance Criteria

- [x] The issues will be updated

## Tasks

- [x] update components/MyIssueDetails
    - [x] Storybook
    - [x] Tests
- [x] Add to app
