### ISSUE TITLE
Add issues

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#12]
## Value proposition

**As a** user
**I need** to have an AddIssueForm and a MyIssues page
**to be able to** create my own issues and navigate between pages

## Description
<img width="700" src="https://user-images.githubusercontent.com/93412094/158961230-00412a18-5b92-44d5-9431-18a8ba66f21d.svg" alt="add issue page with navigation bar" />

## Acceptance Criteria

- [x] The add an issue and the my issues page are available trough a navigation link. 
- [x] I can create my own issues and  they are stored in the local storage.
- [x] By clicking on an issue the detail page appears.

## Tasks

- [x] components/Navigation
    - [x] Add react-router
    - [x] Storybook
    - [x] Tests
- [x] pages/AddForm
    - [x] Add react hook form
    - [x] Storybook
    - [x] Tests
- [x] pages/MyIssues
    - [x] Storybook
    - [x] Tests
- [x] pages/MyIssuesDetail
    - [x] Storybook
    - [x] Tests
- [x] Update styling
- [x] Add to app
