### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#17]
## Value proposition

**As a** user
**I need** to use my GitHub avatar
**to be able to** see the image in the myIssueDetails

## Description
<img width="400" src="https://user-images.githubusercontent.com/93412094/159274668-8e19b4c7-2378-4e90-8267-2e634a81dd67.svg" alt="settings page and details with avatar image" />

## Acceptance Criteria

- [x] On the create page, I can enter my GitHub username
- [x] My GitHub avatar appears in the details of my issues

## Tasks

- [x] Update pages/MyIssueDetails
- [x] Update pages/CreateIssueForm
- [x] Add to app
