### ISSUE TITLE
Sort pinned issues

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#18]
## Value proposition

**As a** user
**I need** to see the pinned issues on top
**to be able to** find them quickly

## Description
<img width="400" src="https://user-images.githubusercontent.com/93412094/159226609-10b5b921-aee2-46e4-981c-6fd677ec2da9.svg" alt="Dashboard with pinned issues at top" />

## Acceptance Criteria

- [x] Pinned issues will appear at the top

## Tasks

- [x] Sort the issues array in the togglePin Function
- [x] Add to app
