### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#19]
## Value proposition

**As a** user
**I need** have a app with clean code
**to be able to** improve the performance

## Description

Code refactoring

## Acceptance Criteria

- [x] Clean code (DRY)

## Tasks

- [x] Outsource Issues from Dashboard and MyIssues page into components
- [x] Generally refactor code
- [x]  sort imports
- [x]  sort styles, check GlobalStyle
- [x]  Outsource headers in components
- [x]  Outsource back arrow in components
- [x]  Change pages/FetchedIssues ⇒ components/FetchedIssues
- [x]  Refactor toggle function
