### ISSUE TITLE
Issue Detail

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#2]
## Value proposition

**As a** user
**I need** to have details on the current issue
**to be able to** analyse the issue

## Description
<img width="300" src="https://user-images.githubusercontent.com/93412094/156604927-d116b2c6-4c0f-4e32-85f1-7c71f7341f79.svg" alt="Detail page" />

## Acceptance Criteria

- [x] Clicking on the issue brings up a detail page
- [x] Clicking on back returns to the dashboard

## Tasks

- [x] pages/Detail
    - [x] Storybook
    - [x] Tests
- [x] Add to app
