### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#20]
## Value proposition

**As a** user
**I need** to have an accessible web application
**to be able to** use them also with physical limitations

## Acceptance Criteria

- [x] Accessibility

## Tasks

- [x] check labels, aria-labels from icons
- [x] check alt text from images
- [x] check labels, aria-labels from input fields
- [x] check labels, aria-labels from buttons
- [x] check contrast
- [x] check font size
- [x] check semantic html
- [x] check tabindex
