### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#26]
## Value proposition

**As a** user
**I need** to have a beautiful GUI
**to be able to** make my eyes happy

## Acceptance Criteria

- [x] Styled App
- [x] Icons for each element in the select box

## Tasks

- [x] Style buttons
- [x] Style details page
- [x] Add icons to react-select box
