### ISSUE TITLE
Pin

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#3]
## Value proposition

**As a** user
**I need** pin issues
**to be able to** find them in the list

## Description
<img width="300" src="https://user-images.githubusercontent.com/93412094/156605821-898be5e5-5673-4002-838b-46a9e92246ec.svg" alt="Dashboard with pins" />

## Acceptance Criteria

- [x] A toggable pin on each issue

## Tasks

- [x] Add pin to issues
    - [x] Update storybook
    - [x] Update styling
    - [x] Update Tests
- [x] Add to app
