### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#30]
## Value proposition

**As a** user
**I need** to switch between all pages
**to be able to** see all open issues

## Description
Add pagination to the each repository
<img width="300" src="https://user-images.githubusercontent.com/93412094/160153325-d743f2c8-d943-42d8-95be-93a6a80583b8.svg" alt="Dashboard buttons for pagination" />

## Acceptance Criteria

- [x] All open issues of a repository can be reached via buttons.

## Tasks

- [x] Add Buttons for pagination
- [x] Update GetFetch function to get the url's
- [x] Update styling
- [x] Update tests
- [x] Check on mobile devices
