### ISSUE TITLE
Refactor 2

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#31]
## Value proposition

**As a** developer
**I need** to have an app with clean code
**to be able to** to have professional pride

## Description

Code refactoring 2

## Acceptance Criteria

- [x] Only the pinned issues are stored in Local storage
- [x] The username is stored in local storage

## Tasks

- [x] Update Tests
- [x] Update Storybook
- [x] Refactor GetData and other functions
