### ISSUE TITLE
State management (Zustand)

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#33]
## Value proposition

**As a** developer
**I need** to have a good state management
**to be able to** make it easier to work with props in React

## Description
Add a state management system

## Acceptance Criteria

- [x] Add Zustand to App

## Tasks

- [x] Install Zustand
- [x] Add useStore
- [x] Change states from useState to useStore
- [x] Update tests
- [x] Check/update Storybook
- [x] Check app
