### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#34]
## Value proposition

**As a** user
**I need** to have a login page
**to be able to** login with my GitHub username

## Description
<img src="https://user-images.githubusercontent.com/93412094/160660639-27427e30-1d4f-4b35-bb4a-2f1efb037937.svg"  width="300" alt="Login page" />

## Acceptance Criteria

- [x] It is possible to login with the Github username

## Tasks

- [x] Add a login page
- [x] Add a profile page
