### ISSUE TITLE
Framer motion

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#35]
## Value proposition

**As a** user
**I need** to have little animations
**to be able to** have a more attractive app

## Description
Small animations in the app

## Acceptance Criteria
- [x] Animated appearance of the header
- [x] Slide-in Navbar
- [x] Animated appearance of the issues

## Tasks

- [x] Add motion to app
- [x] Animated appearance of the issues
- [x] When you start the app, the navbar comes into view from below
- [x] Animated appearance of the issues
- [x] check on mobile devices
