### ISSUE TITLE
Issue overview

### ISSUE THREAD

**Issue by codingoak** [codingoak/capstone-project#39]
## Value proposition

**As a** user
**I need** to have an topic overview
**to be able to** know how many issues are open

## Description
<img src="https://user-images.githubusercontent.com/93412094/160942731-031e29f0-e1ca-466d-9dd6-3ac95519886b.svg" alt="Topic overview" width="300" />

## Acceptance Criteria

- [x] Topic overview for each repository in the dashboard

## Tasks

- [x] Add topic overview
- [x] Update fetch
- [x] Update tests
- [x] Check/update Storybook
